### ISSUE TITLE
Domain management 403s for managers

### ISSUE THREAD

**Issue by widd** [kaiyou/freeposte.io#65] opened 2016-09-17 21:03 UTC
Users that have been given management access of a particular domain get 403 errors on every actual domain management page.

Haven't checked the source yet but I assume it's a simple matter of fixing some permissions on those routes in the flask app.

**Comment by kaiyou** [comment] 2016-09-18 13:20
Are you running the stable branch or the latest builds?

**Comment by widd** [comment] 2016-09-18 21:13
Yep. Stable with everything, and I skipped the dockerized nginx in favor of my own installation on the host machine.

**Comment by kaiyou** [comment] 2016-09-25 09:56
Okay, I can reproduce and it's been a while since the bug was introduced. I will fix it on stable this afternoon. Persmissions have been refactored in the next stable and it should not be a problem anymore.

**Comment by kaiyou** [comment] 2016-09-29 10:18
Indeed the equality test for domains was not written and checking if the domain being accessed was in the list of managed domains was based on object references, which was highly dependent on SQLAlchemy cache.

This is fixed now.

**Closed by kaiyou** 2016-09-29 10:18 UTC
Labels: bug
